### ISSUE TITLE
Tags in recipe in wrong order

### ISSUE THREAD

**Issue by teo-jun-xiong** [AY1920S2-CS2103T-F11-4/main#150]
`recipe add .... t/This t/is t/a t/tag` shows tags as `[tag] [This] [s] [a]` instead of `[This] [is] [a] [tag]`

**Comment by shanecsj** [comment]
Would it be better if the tags are sorted and saved in alphabetical/lexicographical order?

Also, this may be the reason why one of the test case `toModelType_typicalRecipesFile_success()` has failed previously. Will rerun the above test case while attempting to resolve this bug.

**Comment by teo-jun-xiong** [comment]
> Would it be better if the tags are sorted and saved in alphabetical/lexicographical order?
> 
> Also, this may be the reason why one of the test case `toModelType_typicalRecipesFile_success()` has failed previously. Will rerun the above test case while attempting to resolve this bug.

That sounds like a good idea, should be simple to implement.
