### ISSUE TITLE
Modify CookbookSearchByInventoryIngredientsCommand

### ISSUE THREAD

**Issue by teo-jun-xiong** [AY1920S2-CS2103T-F11-4/main#153]
Current implementation simply return recipes that have any ingredients that the inventory has, regardless of quantity.

The intended implementation is to return recipes sorted by the % of ingredients available for the requirements of the recipe.  

We could implement a **divide function** in `MixedFraction`, and use it to **calculate the % complete**. If a recipe requires 10 `a`, 5 `b`, and the inventory has 5 `a`, and 4 `b`:
- For `a`: 50%
- For `b`: 80%
- For the recipe perhaps a simple algorithm to calculate the overall % complete would be to add all the % together and divide by the number of types of ingredients
- In this case: (50+80)/2 = 65%

The command can then make use of % complete to sort the cookbook. Recipes with 0% would not be shown.

**Comment by shanecsj** [comment]
Looks like a good implementation direction for this function.
Maybe we can display this calculated % complete (to nearest integer) on the UI if possible? 
So that the user will be more aware of the search result.

**Comment by teo-jun-xiong** [comment]
> Looks like a good implementation direction for this function.
> Maybe we can display this calculated % complete (to nearest integer) on the UI if possible?
> So that the user will be more aware of the search result.

Sounds good. This will minimize on-the-fly calculations.
